### ISSUE TITLE
Adding new maintainer

### ISSUE THREAD

**Issue by taras** [alphasights/ember-scrollable#22]
Can you please add @Baltazore as a contributor to this library? Also, can you please upgrade me to admin on this repo? 

Or alternatively, can I move this repo to my organization?

**Comment by Arkham** [comment]
Pinging @willrax :)

**Comment by willrax** [comment]
:+1: @Arkham @taras I'll try to get this done today

**Comment by rwwagner90** [comment]
Bump

**Comment by offirgolan** [comment]
@willrax @Arkham there are currently 3 PRs that need to get merged and then versioned. Many people are having issues with ember-light-table since installing this addon as a dependency crashes.

@taras is having some technical issues right now with his computer so if you both need someone to take over in the mean time, I would be happy to get this done for you. I would just need merge + npm publish permissions.

**Comment by willrax** [comment]
Hey @offirgolan you're all set added you to the repo and npm. Sorry for taking so long to move on these things, but thanks for helping out.

**Comment by offirgolan** [comment]
@willrax no problem at all! Thank you for allowing me to help maintain this repo 😄
