### ISSUE TITLE
Missing handling of mouseLeave when mouse button pressed.

### ISSUE THREAD

**Issue by nem-jmalatin** [alphasights/ember-scrollable#59]
There is a problem with situation when dragging scrollbar and leaving the application area while still keeping mouse button pressed.  After reentering into another portion of application viewport, the mousemove events are still consumed by scrollbar. Following code inserted into 
"ember-scrollable\addon\components\ember-scrollable.js"  helped to me:
..
mouseLeave(e){
        if(e.buttons) {
            this.endDrag(e);
        }
    }
..

**Comment by alexander-alvarez** [comment]
Hey, I understand the issue you've expressed... basically if you're out of the browser when you mouse up, the `mouseUp` callback isn't delegated, so when you come back into the browser it still thinks you're scrolling.

The expected behavior is shown here, and with native browsers:
http://noraesae.github.io/perfect-scrollbar/
When you start drag, move off the browser screen, and move the mouse the scrollbar should still scroll.

Do you have bandwidth to investigate?

**Comment by nem-jmalatin** [comment]
In the given example it works nicely, when I drag out of the browser, scrollbars still react , that's OK  , but after mouseUp,  scrollbars disappear instantly and after reentering to the browser at any position they do not react anymore.
This is wished behaviour also for us, but unfortunately, the last point is different, they keep scrolling, even when I reenter the browser and move  mouse over different portion of browser ( and the left button is UP).
This is a bug obviously. I don't know if some bad event handling from our side can influence it this way...
But as I wrote, it helped us to  write handler for mouseLeave inside of ember-scrollable.js.
